### PR TITLE
Create CONTRIBUTING.md

### LINKED ISSUE #48: Add `CONTRIBUTING.md`
### Problem

Currently there is no `CONTRIBUTING.md` file to list the steps for contributing to the project.

Although one can infer the steps from experience with similar projects:

```bash
python -m pip install -e .
yarn
yarn run build
voici build
```

### Suggested Improvement

Let's create `CONTRIBUTING.md` to make it easier for other contributors to get into the project.

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #48 

## Code changes

Add documentation for contributing to the Voici.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
So the UI tests seem to be failing (also noticed in #50):

image

Looks like it could be something related to the latest ipywidgets releases.

cc @martinRenou who might know more about it.

**Comment by martinRenou** [comment]
> cc @martinRenou who might know more about it.

I'm not aware of any recent CSS change in ipywidgets that would cause this

**Comment by jtpio** [comment]
Not necessarily CSS but the widget rendering the error:

image

I'll try to reproduce locally.

**Comment by martinRenou** [comment]
Sorry I missed the widget error view in your screenshot. I thought this was only some padding.

We may want to print the `console.log` to the terminal so that we see the error message.

**Comment by jtpio** [comment]
Hmm it seems to be fine locally:

image

Although not sure CI is doing anything special for the UI tests.

**Comment by jtpio** [comment]
I opened https://github.com/voila-dashboards/voici/issues/53 as a follow-up since this does not seem related to this PR or #50.

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
