### PR TITLE
Wait for service worker on start up

### PR DESCRIPTION
**Pull request by trungleduc**

### CODE REVIEW

**Comment by jtpio** [comment]
Curious what issue does this change fix? Was there some race conditions when a file would be read but the service worker would not be ready yet?

**Comment by trungleduc** [comment]
I heuristically did this in the process of debugging the service worker problem.  Before this change, the worker failed a lot for me, with this chance it feels better, I'm not entirely it would fix anything, but there is no harm in this logic so I decided to keep it.

**Comment by trungleduc** [comment]
Do you have issues with this?

**Comment by jtpio** [comment]
> Do you have issues with this?

No issues, just wanted to understand the motivation because the top comment of the PR was left empty.

**Pull request merged**
